// scripts/curate-words.ts
// Reproducible word-list curation for Longdle.
// Source: lynn/hello-wordl (targets.json + dictionary.json).
// Run: npx tsx scripts/curate-words.ts
// Output: src/data/words.ts

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import seedrandom from 'seedrandom'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')

const SIX_LETTER = /^[a-z]{6}$/
const SHUFFLE_SEED = 'longdle-2026-05-04'
// Cap ANSWERS to the top N most-frequent 6-letter words from the targets list.
// targets.json is ordered by Peter Norvig word frequency (most common first).
// Taking the top 1,800 ensures curated, common words suitable for daily answers.
// Full corpus has ~4,561 six-letter entries; the tail is obscure (e.g. "spinor", "naevus").
const ANSWERS_CAP = 1800

function loadJsonArray(path: string): string[] {
  const raw = JSON.parse(readFileSync(path, 'utf8'))
  if (!Array.isArray(raw)) throw new Error(`${path} is not a JSON array`)
  return raw
}

function filterSixLetter(words: string[]): string[] {
  const seen = new Set<string>()
  const out: string[] = []
  for (const w of words) {
    if (typeof w !== 'string') continue
    const lc = w.toLowerCase()
    if (!SIX_LETTER.test(lc)) continue
    if (seen.has(lc)) continue
    seen.add(lc)
    out.push(lc)
  }
  return out
}

function shuffle<T>(arr: T[], seed: string): T[] {
  const rng = seedrandom(seed)
  const out = arr.slice()
  for (let i = out.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1))
    ;[out[i], out[j]] = [out[j], out[i]]
  }
  return out
}

const targetsRaw = loadJsonArray(resolve(ROOT, 'scripts/raw/targets.json'))
const dictionaryRaw = loadJsonArray(resolve(ROOT, 'scripts/raw/dictionary.json'))

// Preserve frequency order when filtering targets (Norvig frequency list, most common first)
const targetsFiltered = filterSixLetter(targetsRaw).slice(0, ANSWERS_CAP)
const dictionaryFiltered = filterSixLetter(dictionaryRaw)

// D-03: VALID_GUESSES MUST be a superset of ANSWERS.
const guessUnion = new Set<string>([...dictionaryFiltered, ...targetsFiltered])
const validGuesses = [...guessUnion].sort() // sorting VALID_GUESSES is OK; only ANSWERS must NOT be sorted.

// D-02 / WORDS-03: ANSWERS must NOT be alphabetically sorted in source.
const answers = shuffle(targetsFiltered, SHUFFLE_SEED)

// Hard sanity gates — fail loudly if curation drifts outside expected bounds.
if (answers.length < 800) {
  throw new Error(`ANSWERS too small: ${answers.length} (expected >= 800; see RESEARCH.md A2)`)
}
if (answers.length > 2500) {
  throw new Error(`ANSWERS too large: ${answers.length} (expected <= 2500; see RESEARCH.md A2)`)
}
if (validGuesses.length < 5000) {
  throw new Error(`VALID_GUESSES too small: ${validGuesses.length} (expected >= 5000; see RESEARCH.md A6)`)
}
if (validGuesses.length > 20000) {
  throw new Error(`VALID_GUESSES too large: ${validGuesses.length} (expected <= 20000; see RESEARCH.md A6)`)
}
// D-03 enforcement: every answer must be in valid guesses.
for (const a of answers) {
  if (!guessUnion.has(a)) throw new Error(`D-03 violation: answer ${a} missing from VALID_GUESSES`)
}

const banner = `// AUTO-GENERATED by scripts/curate-words.ts. Do not edit by hand.
// Source corpus: lynn/hello-wordl (targets.json + dictionary.json).
// Shuffle seed: '${SHUFFLE_SEED}'  (re-run the script to regenerate deterministically).
// ANSWERS count: ${answers.length}; VALID_GUESSES count: ${validGuesses.length}.
// WORDS-03: ANSWERS is shuffled, NOT sorted alphabetically (sorting leaks upcoming words).
`

const body = `${banner}
export const ANSWERS: readonly string[] = ${JSON.stringify(answers, null, 0)} as const

export const VALID_GUESSES: readonly string[] = ${JSON.stringify(validGuesses, null, 0)} as const

export const VALID_WORDS: ReadonlySet<string> = new Set<string>([...ANSWERS, ...VALID_GUESSES])
`

const outPath = resolve(ROOT, 'src/data/words.ts')
mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, body, 'utf8')

console.log(`Wrote ${outPath}`)
console.log(`  ANSWERS: ${answers.length}`)
console.log(`  VALID_GUESSES: ${validGuesses.length}`)
